import React from 'react';
import { Lightbulb, FlaskConical } from 'lucide-react';
import { MindMapData } from '../types';

interface ReportViewProps {
  data: MindMapData;
}

const ReportView: React.FC<ReportViewProps> = ({ data }) => {
  return (
    <div className="h-full overflow-y-auto p-8 bg-white">
      <div className="max-w-2xl mx-auto">
         <div className="flex items-center gap-3 mb-6">
            <div className="bg-amber-100 p-2 rounded-lg">
                <FlaskConical className="w-6 h-6 text-amber-600" />
            </div>
            <div>
                <h2 className="text-2xl font-bold text-slate-800">Research Directions</h2>
                <p className="text-sm text-slate-500">AI-suggested future work & extensions</p>
            </div>
         </div>
         
         <div className="prose prose-slate prose-sm sm:prose-base max-w-none">
            <div className="bg-amber-50 border border-amber-100 p-4 rounded-lg mb-6 text-amber-900 text-sm flex gap-2">
                <Lightbulb className="w-5 h-5 shrink-0" />
                <p className="m-0">
                    This report analyzes the limitations and results of the current paper to suggest potential areas for further academic exploration.
                </p>
            </div>

            {/* Markdown Rendering */}
            {data.researchReport.split('\n').map((line, idx) => {
                const trimmed = line.trim();
                if (!trimmed) return <div key={idx} className="h-4" />;
                if (trimmed.startsWith('#')) return <h3 key={idx} className="font-bold text-lg mt-4 mb-2 text-slate-800">{trimmed.replace(/^#+\s*/, '')}</h3>;
                if (trimmed.startsWith('-')) return <li key={idx} className="ml-4 list-disc marker:text-amber-500">{trimmed.replace(/^-\s*/, '')}</li>;
                if (trimmed.match(/^\d+\./)) return <li key={idx} className="ml-4 list-decimal marker:text-amber-600 font-medium mt-2">{trimmed.replace(/^\d+\.\s*/, '')}</li>;
                return <p key={idx} className="mb-2 leading-relaxed text-slate-700">{trimmed}</p>;
            })}
         </div>

         <div className="mt-8 pt-8 border-t border-slate-100 text-center text-xs text-slate-400">
            Generated by Gemini 2.5 Flash • Suggestions based on text analysis
         </div>
      </div>
    </div>
  );
};

export default ReportView;