import React from 'react';
import { FileText } from 'lucide-react';
import { MindMapData } from '../types';

interface SummaryViewProps {
  data: MindMapData;
}

const SummaryView: React.FC<SummaryViewProps> = ({ data }) => {
  return (
    <div className="h-full overflow-y-auto p-8 bg-white">
      <div className="max-w-2xl mx-auto">
         <div className="flex items-center gap-3 mb-6">
            <div className="bg-emerald-100 p-2 rounded-lg">
                <FileText className="w-6 h-6 text-emerald-600" />
            </div>
            <div>
                <h2 className="text-2xl font-bold text-slate-800">Abstract</h2>
                <p className="text-sm text-slate-500">AI-generated overview (Chinese)</p>
            </div>
         </div>
         
         <div className="prose prose-slate prose-sm sm:prose-base max-w-none">
            {/* Simple Markdown rendering for the summary. 
                For a production app, use 'react-markdown' here. 
                We will simulate paragraph breaks for now. */}
            {data.markdownSummary.split('\n').map((line, idx) => {
                const trimmed = line.trim();
                if (!trimmed) return <div key={idx} className="h-4" />;
                if (trimmed.startsWith('#')) return <h3 key={idx} className="font-bold text-lg mt-4 mb-2">{trimmed.replace(/^#+\s*/, '')}</h3>;
                if (trimmed.startsWith('-')) return <li key={idx} className="ml-4 list-disc">{trimmed.replace(/^-\s*/, '')}</li>;
                return <p key={idx} className="mb-2 leading-relaxed text-slate-700">{trimmed}</p>;
            })}
         </div>

         <div className="mt-8 pt-8 border-t border-slate-100 text-center text-xs text-slate-400">
            Generated by Gemini 2.5 Flash based on PDF extraction
         </div>
      </div>
    </div>
  );
};

export default SummaryView;